export const GET_EMPLOYEES = 'GET_EMPLOYEES'
export const GET_EMPLOYEE_BY_ID = 'GET_EMPLOYEE_BYid'
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const UPDATE_EMPLOYEE_BY_ID = 'UPDATE_EMPLOYEE_BYid'
export const DELETE_EMPLOYEE_BY_ID = 'DELETE_EMPLOYEE_BYid'

// export const GET_PROVINCE = 'GET_PROVINCE'
// export const GET_DISTRICT = 'GET_DISTRICT'
// export const GET_COMMUNE = 'GET_COMMUNE'